# This file was generated by the Subetter release workflow. DO NOT EDIT.
#
# 每次发布新版本时由发布流水线自动重新生成并推送到本仓库（b0y1/homebrew-taps）。
# 发布与升级说明见 Subetter 官方发布仓库：https://github.com/b0y1/subetter-release
cask "subetter" do
  version "0.4.0"
  sha256 "a1c4c36898b37d22f70d1a8fd28115f2a8ac7e967bbd9bafff1ac2776b49b942"

  url "https://github.com/b0y1/subetter-release/releases/download/v#{version}/Subetter_#{version}_universal.dmg"
  name "Subetter"
  desc "Extract subtitles and audio tracks from local videos for language learning"
  homepage "https://github.com/b0y1/subetter-release"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: :sequoia

  app "Subetter.app"

  postflight_steps do
    # 安装包未进行 Apple 公证（ad-hoc 签名）。下载后会被打上隔离标记，
    # 不去掉的话首次打开会被 Gatekeeper 拦下报「已损坏」。
    # 路径必须用 {{appdir}} 模板：steps 块在独立 DSL 上求值，拿不到 cask 的 appdir 方法；
    # 也不能写 postflight，Homebrew 7 已废弃它（改用 *_steps + 规范化步骤）。
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Subetter.app"]
  end

  caveats <<~EOS
    Subetter 未进行 Apple 公证，安装时已自动清除隔离标记。
    若打开时仍提示「已损坏」，请手动执行：
      xattr -dr com.apple.quarantine /Applications/Subetter.app

    应用数据位于 ~/Library/Application Support/app.subetter.desktop。
    想连数据一起清理，用 --zap：
      brew uninstall --cask --zap subetter
  EOS

  zap trash: [
    "~/Library/Application Support/app.subetter.desktop",
    "~/Library/Caches/app.subetter.desktop",
    "~/Library/Preferences/app.subetter.desktop.plist",
    "~/Library/Saved Application State/app.subetter.desktop.savedState",
    "~/Library/Logs/app.subetter.desktop",
  ]
end
